/*Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. */
const MIN_VALUE_DATA_SOURCE_DATA_PROVIDER = 1;
const MAX_VALUE_DATA_SOURCE_DATA_PROVIDER = 15;
const EXCHANGE_RATE_TYPE_PATTERN = /^[A-Za-z0-9]{1,15}$/;
const CURRENCY_CODE_PATTERN = /^[A-Z]{3}$/;
const DEFAULT_VALUE_FOR_IS_DIRECT_VALUE = false;
const DEFAULT_VALUE_FOR_CURRENCY_FACTORS = 1;
const DEFAULT_VALUE_FOR_IS_INVERSION_ALLOWED_VALUE = false;
const CREATE_EVENT = 'CREATE';
const DESTINATION_NAME_PATTERN = /^[A-Za-z0-9]{1,200}$/;
const MIN_VALUE_LOCALE = 1;
const MAX_VALUE_LOCALE = 14;
const MIN_VALUE_EXCHANGE_RATE_TYPE_DESCRIPTION = 1;
const MAX_VALUE_EXCHANGE_RATE_TYPE_DESCRIPTION = 30;

module.exports = {
  MIN_VALUE_DATA_SOURCE_DATA_PROVIDER,
  MAX_VALUE_DATA_SOURCE_DATA_PROVIDER,
  EXCHANGE_RATE_TYPE_PATTERN,
  CURRENCY_CODE_PATTERN,
  DEFAULT_VALUE_FOR_IS_DIRECT_VALUE,
  DEFAULT_VALUE_FOR_CURRENCY_FACTORS,
  DEFAULT_VALUE_FOR_IS_INVERSION_ALLOWED_VALUE,
  CREATE_EVENT,
  DESTINATION_NAME_PATTERN,
  MIN_VALUE_LOCALE,
  MAX_VALUE_LOCALE,
  MIN_VALUE_EXCHANGE_RATE_TYPE_DESCRIPTION,
  MAX_VALUE_EXCHANGE_RATE_TYPE_DESCRIPTION
};
